# 协议定义文件
# section 命名规则: [protocol.<name>]
# 可在 gateway.ini 的 [device].serial_protocols 中按设备顺序引用

[protocol.ble_mesh_default]
connection_type = ble_mesh
frame_header = F1DD
# 留空表示不校验帧尾
frame_tail =
id_len = 2
mesh_cmd_prefix = AT+MESH

[protocol.ble_mesh_private_a]
connection_type = ble_mesh
frame_header = F2DD
# 留空表示不校验帧尾
frame_tail =
id_len = 2
mesh_cmd_prefix = AT+MESH
